[build]
  # Build command for React apps
  command = "npm run build"
  
  # Directory to publish (where the built files are)
  publish = "build"

[build.environment]
  # Node.js version for the build
  NODE_VERSION = "18"

# Redirect rules for Single Page Application (SPA)
# This ensures all routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000"
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Specific caching for HTML files (shorter cache)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Specific caching for service worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"
